import ProjectDescription

let workspace = Workspace(
  name: "ShikiWorkspace",
  projects: [
    "apps/**",
    "features/**",
    "packages/**",
  ],
  generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
